### ISSUE TITLE
commit 80b10107cb2703d63fb14c90e2be442c0724836d breaks build with linux headers 3.13

### ISSUE THREAD

**Issue by balducci** [gentoo/eudev#87]
hello,

I have been pointed here by the committer:

```
commit 80b10107cb2703d63fb14c90e2be442c0724836d
builtins: add <linux/fcntl.h> for uclibc
```

Apparently, the above commit breaks eudev build for me

Running glibc-2.18 with 3.13.2 kernel headers:

GNU C Library (GNU libc) stable release version 2.18, by Roland McGrath et al.
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.2.
Compiled on a Linux 3.13.2 system on 2014-02-10.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
http://www.gnu.org/software/libc/bugs.html.

Getting errors like this:

```
gcc -m64 -DHAVE_CONFIG_H -I. -I../..  -I ../../src/libudev -I ../../src/udev   -I/usr/Xorg/include -MT accelerometer.o -MD -MP -MF .deps/accelerometer.Tpo -c -o accelerometer.o accelerometer.c
In file included from /usr/include/asm/fcntl.h:1:0,
                 from /usr/include/linux/fcntl.h:4,
                 from accelerometer.c:60:
/usr/include/asm-generic/fcntl.h:179:8: error: redefinition of 'struct flock'
 struct flock {
        ^
In file included from /usr/include/fcntl.h:35:0,
                 from accelerometer.c:53:

....
```

Build succeeds if:

```
=> I run with -DHAVE_ARCH_STRUCT_FLOCK
```

or
    => I tweak all <linux/fcntl.h> into <fcntl.h>

I am told by tony (the committer) that build is fine w/ glibc-2.17, so
the problem might be the kernel headers

I am sorry: I am not able to go deeper

I will be happy to send in any other detail that might help

thanks a lot
ciao
gabriele
